### PR TITLE
updated http calls for https; soon the Quandl API will only be accept…

### PR DESCRIPTION
**Pull request by brianrisk**
…ing https calls

### CODE REVIEW

**Comment by fu-zev** [comment]
Thanks for you remind. It has been updated.

**Comment by ldsanders2807** [comment]
THANK YOU!  Have a great week end.

LaVerne Sanders

**Comment by ldsanders2807** [comment]
Hello again,

It seems that on June 23rd, last Tuesday, the download process ceased to function.

The people at Quandl say it has to do with the API .  I’m using the one you provided last month to use “HTTPS”.

The download files contain the following text:

<html>

<head><title>301 Moved Permanently</title></head>

<body bgcolor="white">

<center><h1>301 Moved Permanently</h1></center>

<hr><center>nginx/1.4.6 (Ubuntu)</center>

</body>

</html>

Thanks again for your help.

LaVerne Sanders

**Comment by brianrisk** [comment]
@ldsanders2807 it turns out my original fix didn't get to the root of it -- the calls were still being made in HTTP.  I showed this to a colleague who is better at C than I and he is looking into a solution.  Initially a curl solution was put together -- this works, but it creates a curl dependency so would impact cross-platform nature (esp. on windows).  He is looking into a boos solution.

**Comment by brianrisk** [comment]
@zafuer do you have any suggestions?

**Comment by malickf** [comment]
I think that the code need to be rewritten and the next version will need to use openSSL to be able to establish a ssl connection.  I may try to do it and to publish it here since i need it for a personnal project. However it will probably rely on the boost asio library.

**Comment by ldsanders2807** [comment]
Is there any available C++ or C# or VB code examples available that will successfully download thru Quandl's HTTPS?

**Comment by brianrisk** [comment]
@ldsanders2807 Here is a full list of libraries that access the Quandl API:

https://www.quandl.com/tools/full-list

**Comment by ldsanders2807** [comment]
Any progress with the boost asio library version?

**Comment by brianrisk** [comment]
@ldsanders2807, if @malickf has some cross-platofrm ideas for how to integrate openSSL, that would be the preferred path.

**Comment by ldsanders2807** [comment]
I have not been able to make heads or tales out of the C# code.  So, any C++ path would be awesome! :-)

**Comment by malickf** [comment]
@brianrisk, I ll try to post it  next Week, i m very busy actualy.  + i also need to learn git , i m a newbie with it ;)

**Comment by brianrisk** [comment]
@malickf if you can help with openSSL, I can help with git!

**Comment by malickf** [comment]
Hi, I succeed to implement a working version, however the code is deeply modified (cross plateform, rely on boost + open ssl) so could you please tell me if I should post it here as a branch or should I create a repo on my Git page ? Thanks

**Comment by ldsanders2807** [comment]
That's great news malickf!  Looking forward to trying your example.  Hopefully Brian can direct where to put it.

**Comment by ldsanders2807** [comment]
Where did you  get the open ssl library files?

**Comment by malickf** [comment]
I have added to my profile the code and changed the readme. Sorry if it is not the correct way to proceed it is my first fork. 
- @ldsanders2807  read the 2nd post about ssl for more information.

**Comment by ldsanders2807** [comment]
Thanks for your work on these routines!  I have my system up and running again.

LaVerne Sanders

**Comment by malickf** [comment]
@ldsanders2807 Thank you !

**Pull request closed without merging**
